"""
NutriSync - Module 5: USDA Nutrition Database
==============================================
Purpose:
    Local nutrition lookup for user's ingredients.
    Prevents LLM hallucination by grounding all
    nutrition values in verified USDA data BEFORE
    the prompt is built.

What this module does:
    1. Loads USDA CSV into SQLite (one-time setup)
    2. Fuzzy matches user ingredient text to DB entries
    3. Returns nutrition per 100g for each ingredient
    4. Builds combined nutrition map for prompt builder

Dependencies:
    - pandas
    - sqlite3 (built-in)
    - difflib (built-in, fuzzy matching)
    - rapidfuzz (optional, better matching - install if possible)
        pip install rapidfuzz

Usage:
    from modules.module5_usda_database import USDADatabase
    db = USDADatabase()
    result = db.lookup_ingredients(["chicken breast", "spinach", "rice"])

Author: NutriSync Project
"""

import sqlite3
import os
import pandas as pd
from difflib import SequenceMatcher
from typing import Optional

# ─── Try to import rapidfuzz for better matching ────────────────────────────
# rapidfuzz is significantly faster and more accurate than difflib
# If not installed, difflib is used as fallback (still works well)
try:
    from rapidfuzz import fuzz, process as rfprocess
    RAPIDFUZZ_AVAILABLE = True
except ImportError:
    RAPIDFUZZ_AVAILABLE = False


# ─── Path Configuration ─────────────────────────────────────────────────────
BASE_DIR       = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR       = os.path.join(BASE_DIR, "data", "raw")
DB_DIR         = os.path.join(BASE_DIR, "database")
DB_PATH        = os.path.join(DB_DIR, "nutrisync.db")

# Path to processed USDA CSV
# Generated by: python data/usda_processor.py --foundation_dir ... --sr_legacy_dir ...
USDA_CSV_PATH  = os.path.join(BASE_DIR, "data", "processed", "usda_nutrition_processed.csv")


# ─── USDA Database Class ─────────────────────────────────────────────────────
class USDADatabase:
    """
    Handles all USDA nutrition data operations.

    Typical flow:
        db = USDADatabase()           # auto-initializes DB if needed
        result = db.lookup_ingredients(["chicken breast", "spinach"])
        # Returns full nutrition map for prompt builder
    """

    # Minimum similarity score (0-100) to accept a fuzzy match
    # 60 = lenient (catches more, may have false positives)
    # 75 = balanced (recommended)
    # 85 = strict (misses some valid matches)
    MATCH_THRESHOLD = 60

    def __init__(self, db_path: str = DB_PATH, csv_path: str = USDA_CSV_PATH):
        self.db_path  = db_path
        self.csv_path = csv_path
        self._food_names_cache = None  # cached for fast fuzzy matching

        # Ensure database directory exists
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)

        # Initialize DB if it doesn't exist or table is empty
        if not self._db_has_data():
            print("[Module 5] Database not found or empty. Building from CSV...")
            self._load_csv_to_sqlite()
        else:
            print("[Module 5] USDA database ready.")

        # Pre-load all food names into memory for fast fuzzy search
        self._cache_food_names()

    # ────────────────────────────────────────────────────────────────────────
    # PUBLIC METHODS (used by other modules)
    # ────────────────────────────────────────────────────────────────────────

    def lookup_ingredients(self, ingredients: list[str]) -> dict:
        """
        Main method called by Module 6 (Prompt Builder).

        Given a list of ingredient strings from user input,
        returns a nutrition map for all matched ingredients.

        Args:
            ingredients: List of ingredient strings
                         e.g. ["chicken breast", "spinach", "basmati rice"]

        Returns:
            dict: {
                "matched": {
                    "chicken breast": {
                        "matched_to": "chicken breast raw",
                        "match_score": 95,
                        "calories_per_100g": 165,
                        "protein_g": 31.0,
                        ...
                    },
                    ...
                },
                "not_found": ["mystery ingredient"],
                "summary": {
                    "total_ingredients_searched": 3,
                    "total_matched": 2,
                    "total_not_found": 1
                }
            }
        """
        result = {
            "matched": {},
            "not_found": [],
            "summary": {}
        }

        for ingredient in ingredients:
            ingredient_clean = ingredient.strip().lower()
            if not ingredient_clean:
                continue

            nutrition = self._find_ingredient(ingredient_clean)

            if nutrition:
                result["matched"][ingredient] = nutrition
            else:
                result["not_found"].append(ingredient)

        result["summary"] = {
            "total_ingredients_searched": len(ingredients),
            "total_matched": len(result["matched"]),
            "total_not_found": len(result["not_found"])
        }

        return result

    def lookup_single(self, ingredient: str) -> Optional[dict]:
        """
        Look up a single ingredient.
        Returns nutrition dict or None if not found.

        Args:
            ingredient: Single ingredient string

        Returns:
            dict with nutrition data or None
        """
        return self._find_ingredient(ingredient.strip().lower())

    def get_all_ingredients(self) -> list[str]:
        """
        Returns full list of all ingredient names in DB.
        Useful for autocomplete in frontend.
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute("SELECT food_name FROM usda_nutrition ORDER BY food_name")
        names = [row[0] for row in cursor.fetchall()]
        conn.close()
        return names

    def search_by_category(self, category: str) -> list[dict]:
        """
        Returns all ingredients in a given category.
        Useful for browsing available ingredients.

        Categories: Poultry, Beef, Fish, Vegetables,
                    Grains, Dairy, Legumes, etc.
        """
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute(
            "SELECT * FROM usda_nutrition WHERE LOWER(category) = LOWER(?)",
            (category,)
        )
        rows = [dict(row) for row in cursor.fetchall()]
        conn.close()
        return rows

    def get_database_stats(self) -> dict:
        """Returns stats about the loaded database."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute("SELECT COUNT(*) FROM usda_nutrition")
        total = cursor.fetchone()[0]

        cursor.execute(
            "SELECT category, COUNT(*) as count FROM usda_nutrition "
            "GROUP BY category ORDER BY count DESC"
        )
        categories = {row[0]: row[1] for row in cursor.fetchall()}

        conn.close()
        return {
            "total_ingredients": total,
            "categories": categories,
            "fuzzy_engine": "rapidfuzz" if RAPIDFUZZ_AVAILABLE else "difflib",
            "match_threshold": self.MATCH_THRESHOLD
        }

    # ────────────────────────────────────────────────────────────────────────
    # PRIVATE METHODS (internal logic)
    # ────────────────────────────────────────────────────────────────────────

    def _db_has_data(self) -> bool:
        """Check if SQLite DB exists and has data."""
        if not os.path.exists(self.db_path):
            return False
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            cursor.execute(
                "SELECT name FROM sqlite_master "
                "WHERE type='table' AND name='usda_nutrition'"
            )
            table_exists = cursor.fetchone() is not None
            if table_exists:
                cursor.execute("SELECT COUNT(*) FROM usda_nutrition")
                count = cursor.fetchone()[0]
                conn.close()
                return count > 0
            conn.close()
            return False
        except Exception:
            return False

    def _load_csv_to_sqlite(self):
        """
        One-time setup: Load USDA CSV into SQLite database.

        For production USDA data:
            The real USDA CSV has different column names.
            You'll need to map them to our schema below.
            Check USDA_COLUMN_MAPPING at bottom of this file.
        """
        if not os.path.exists(self.csv_path):
            raise FileNotFoundError(
                f"USDA CSV not found at: {self.csv_path}\n"
                f"Run: python data/raw/create_sample_usda.py\n"
                f"Or download real data from: https://fdc.nal.usda.gov/download-foods"
            )

        print(f"[Module 5] Loading USDA data from: {self.csv_path}")
        df = pd.read_csv(self.csv_path)

        # Add lowercase search column for faster matching
        df['food_name_lower'] = df['food_name'].str.lower().str.strip()

        # Write to SQLite
        conn = sqlite3.connect(self.db_path)
        df.to_sql('usda_nutrition', conn, if_exists='replace', index=False)

        # Create index on food_name for faster queries
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_food_name "
            "ON usda_nutrition(food_name_lower)"
        )
        conn.commit()
        conn.close()

        print(f"[Module 5] Loaded {len(df)} ingredients into database.")

    def _cache_food_names(self):
        """
        Load all food names into memory for fuzzy matching.
        This avoids repeated DB queries during matching.
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute("SELECT food_name_lower FROM usda_nutrition")
        self._food_names_cache = [row[0] for row in cursor.fetchall()]
        conn.close()

    def _find_ingredient(self, query: str) -> Optional[dict]:
        """
        Core search function.
        1. Try exact match first (fastest)
        2. Try partial/contains match
        3. Try fuzzy match (slowest but catches typos/variations)

        Args:
            query: Lowercase ingredient string from user

        Returns:
            dict with nutrition data and match metadata, or None
        """
        if not self._food_names_cache:
            self._cache_food_names()

        # ── Step 1: Exact match ───────────────────────────────────────────
        exact = self._db_query_exact(query)
        if exact:
            exact['match_type'] = 'exact'
            exact['match_score'] = 100
            return exact

        # ── Step 2: Contains match ────────────────────────────────────────
        # "chicken" matches "chicken breast raw"
        contains = self._db_query_contains(query)
        if contains:
            contains['match_type'] = 'contains'
            return contains

        # ── Step 3: Fuzzy match ───────────────────────────────────────────
        # "chiken brest" matches "chicken breast raw"
        fuzzy = self._fuzzy_match(query)
        if fuzzy:
            fuzzy['match_type'] = 'fuzzy'
            return fuzzy

        return None

    def _db_query_exact(self, query: str) -> Optional[dict]:
        """Direct SQL exact match on lowercase food name."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute(
            "SELECT * FROM usda_nutrition WHERE food_name_lower = ?",
            (query,)
        )
        row = cursor.fetchone()
        conn.close()
        if row:
            return self._format_nutrition_row(dict(row), query, 100)
        return None

    # Substrings that indicate a non-whole-food USDA entry.
    # "chicken" should match "Chicken, broilers, breast, raw"
    # NOT "Chicken, meatless" / "Fat, chicken" / "Chicken broth, canned"
    _DEPRIORITISE_SUBSTRINGS = [
        "meatless", "broth", "stock", "canned", "nugget", "rice bran",
        "eggnog", "eggplant", "imitation", "fat, ", "dehydrated",
        " sauce", "gravy", "condensed", "vinegar", "flavoring",
        "baby food", "infant", "formula", "substitute", "powder,",
        "drink", "beverage", "spread", "extract,",
        # additional entries causing wrong matches
        "flour", "dried", "yolk", "albumin", "mix,", "batter",
        "product", "coating", "breaded", "bran,", "germ,",
        "flakes", "puff", "cereal", "cake", "cookie", "cracker",
        "noodle", "pasta", "starch", "syrup", "oil,",
        "unenriched", "black,", "black rice", "red,", "red rice",
        "wild rice", "glutinous", "sprouted",
    ]

    # Preferred categories — whole ingredient categories get boosted
    _PREFERRED_CATEGORIES = {
        "Poultry Products", "Finfish and Shellfish Products",
        "Beef Products", "Pork Products", "Dairy and Egg Products",
        "Vegetables and Vegetable Products", "Cereal Grains and Pasta",
        "Legumes and Legume Products", "Nut and Seed Products",
        "Fruits and Fruit Juices", "Lamb, Veal, and Game Products",
        "Spices and Herbs",
    }

    def _db_query_contains(self, query: str) -> Optional[dict]:
        """
        SQL LIKE match: searches for query string within food names.

        Ranking priority (highest to lowest):
          1. Name starts with query  +  preferred category  +  not deprioritised
          2. Name starts with query  +  not deprioritised
          3. Name contains query     +  preferred category  +  not deprioritised
          4. Name contains query     +  not deprioritised
          5. Name starts with query  (any — fallback)
          6. Name contains query     (any — last resort)
        """
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        # Fetch top 60 candidates containing the query string
        cursor.execute(
            "SELECT * FROM usda_nutrition "
            "WHERE food_name_lower LIKE ? "
            "ORDER BY LENGTH(food_name_lower) ASC "
            "LIMIT 60",
            (f'%{query}%',)
        )
        candidates = [dict(r) for r in cursor.fetchall()]

        if not candidates:
            # Try individual words from a multi-word query
            words = query.split()
            if len(words) > 1:
                for word in words:
                    if len(word) > 3:
                        cursor.execute(
                            "SELECT * FROM usda_nutrition "
                            "WHERE food_name_lower LIKE ? "
                            "ORDER BY LENGTH(food_name_lower) ASC "
                            "LIMIT 60",
                            (f'%{word}%',)
                        )
                        candidates = [dict(r) for r in cursor.fetchall()]
                        if candidates:
                            break

        conn.close()
        if not candidates:
            return None

        # ── Rank candidates ───────────────────────────────────────────────
        import re as _re
        def _rank(row):
            name     = row["food_name_lower"]
            name_raw = row.get("food_name", name)   # original case for brand check
            cat      = row.get("category", "")

            is_bad      = any(s in name for s in self._DEPRIORITISE_SUBSTRINGS)
            in_pref_cat = cat in self._PREFERRED_CATEGORIES
            starts_with = name.startswith(query)

            # Brand signal: ALL-CAPS words 3+ chars in original name
            # e.g. "UNCLE BEN'S", "KRAFT", "USDA"
            has_brand = bool(_re.search(r'\b[A-Z]{3,}\b', name_raw))
            if has_brand:
                is_bad = True

            # Whole-food signal: name contains "raw" or ", cooked"
            is_whole = ("raw" in name or ", cooked" in name
                        or "fresh" in name or "whole," in name)

            if starts_with and is_whole and not is_bad and in_pref_cat: return (0, len(name))
            if starts_with and not is_bad and in_pref_cat:              return (1, len(name))
            if is_whole and not is_bad and in_pref_cat:                 return (2, len(name))
            if starts_with and not is_bad:                              return (3, len(name))
            if not is_bad and in_pref_cat:                              return (4, len(name))
            if not is_bad:                                              return (5, len(name))
            if starts_with:                                             return (6, len(name))
            return (7, len(name))

        best = sorted(candidates, key=_rank)[0]
        score = self._similarity_score(query, best["food_name_lower"])
        return self._format_nutrition_row(best, query, score)

    def _fuzzy_match(self, query: str) -> Optional[dict]:
        """
        Fuzzy string matching against all cached food names.
        Uses rapidfuzz if available, otherwise difflib.
        """
        if not self._food_names_cache:
            return None

        if RAPIDFUZZ_AVAILABLE:
            # rapidfuzz is much faster on large datasets
            matches = rfprocess.extractOne(
                query,
                self._food_names_cache,
                scorer=fuzz.WRatio,
                score_cutoff=self.MATCH_THRESHOLD
            )
            if matches:
                best_name, score, _ = matches
            else:
                return None
        else:
            # difflib fallback
            best_name = None
            best_score = 0
            for food_name in self._food_names_cache:
                score = self._similarity_score(query, food_name) * 100
                if score > best_score:
                    best_score = score
                    best_name = food_name
            score = best_score
            if score < self.MATCH_THRESHOLD:
                return None

        # Fetch full row for the best match
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute(
            "SELECT * FROM usda_nutrition WHERE food_name_lower = ?",
            (best_name,)
        )
        row = cursor.fetchone()
        conn.close()

        if row:
            return self._format_nutrition_row(dict(row), query, round(score))
        return None

    def _similarity_score(self, s1: str, s2: str) -> float:
        """Calculate similarity score between two strings (0-1)."""
        return SequenceMatcher(None, s1, s2).ratio()

    def _format_nutrition_row(
        self, row: dict, query: str, match_score: int
    ) -> dict:
        """
        Format a raw DB row into clean nutrition output.
        This is what gets returned to Module 6.
        """
        return {
            "matched_to"        : row.get('food_name', 'unknown'),
            "match_score"       : match_score,
            "category"          : row.get('category', 'unknown'),

            # Core macros (per 100g)
            "calories_per_100g" : round(float(row.get('calories',    0) or 0), 1),
            "protein_g"         : round(float(row.get('protein_g',   0) or 0), 1),
            "carbs_g"           : round(float(row.get('carbs_g',     0) or 0), 1),
            "fat_g"             : round(float(row.get('fat_g',       0) or 0), 1),
            "fiber_g"           : round(float(row.get('fiber_g',     0) or 0), 1),

            # Key micronutrients (per 100g)
            "iron_mg"           : round(float(row.get('iron_mg',     0) or 0), 2),
            "magnesium_mg"      : round(float(row.get('magnesium_mg',0) or 0), 1),
            "calcium_mg"        : round(float(row.get('calcium_mg',  0) or 0), 1),
            "potassium_mg"      : round(float(row.get('potassium_mg',0) or 0), 1),
            "sodium_mg"         : round(float(row.get('sodium_mg',   0) or 0), 1),
            "vitamin_c_mg"      : round(float(row.get('vitamin_c_mg',0) or 0), 1),
            "omega3_g"          : round(float(row.get('omega3_g',    0) or 0), 2),
        }


# ─── USDA Column Mapping for REAL USDA FoodData Central CSV ─────────────────
# When you download the real USDA data, the columns will be different.
# Use this mapping to rename them to our schema before loading.
#
# Real USDA CSV columns → Our schema columns:
#
# USDA "foundation_food.csv":
#   'fdc_id'                    → 'fdc_id'
#   'description'               → 'food_name'
#   'Energy'                    → 'calories'
#   'Protein'                   → 'protein_g'
#   'Carbohydrate, by difference' → 'carbs_g'
#   'Total lipid (fat)'         → 'fat_g'
#   'Fiber, total dietary'      → 'fiber_g'
#   'Sugars, total including NLEA' → 'sugar_g'
#   'Sodium, Na'                → 'sodium_mg'
#   'Iron, Fe'                  → 'iron_mg'
#   'Magnesium, Mg'             → 'magnesium_mg'
#   'Calcium, Ca'               → 'calcium_mg'
#   'Potassium, K'              → 'potassium_mg'
#   'Vitamin C'                 → 'vitamin_c_mg'
#   'Vitamin D'                 → 'vitamin_d_mcg'
#   'Fatty acids, total omega-3' → 'omega3_g'
#
# Use this function to load real USDA data:
def load_real_usda_data(real_csv_path: str, db_path: str = DB_PATH):
    """
    Load real USDA FoodData Central data into SQLite.
    Run this ONCE when setting up with real data.

    Args:
        real_csv_path: Path to downloaded USDA CSV
        db_path: Path to SQLite database
    """
    COLUMN_MAPPING = {
        'description'                      : 'food_name',
        'Energy'                           : 'calories',
        'Protein'                          : 'protein_g',
        'Carbohydrate, by difference'      : 'carbs_g',
        'Total lipid (fat)'                : 'fat_g',
        'Fiber, total dietary'             : 'fiber_g',
        'Sugars, total including NLEA'     : 'sugar_g',
        'Sodium, Na'                       : 'sodium_mg',
        'Iron, Fe'                         : 'iron_mg',
        'Magnesium, Mg'                    : 'magnesium_mg',
        'Calcium, Ca'                      : 'calcium_mg',
        'Potassium, K'                     : 'potassium_mg',
        'Vitamin C, total ascorbic acid'   : 'vitamin_c_mg',
        'Vitamin D (D2 + D3)'              : 'vitamin_d_mcg',
        'Fatty acids, total omega-3'       : 'omega3_g',
    }

    df = pd.read_csv(real_csv_path)
    df = df.rename(columns=COLUMN_MAPPING)

    # Keep only columns we need
    keep_cols = list(COLUMN_MAPPING.values()) + ['fdc_id']
    available = [c for c in keep_cols if c in df.columns]
    df = df[available]

    # Fill missing values
    numeric_cols = df.select_dtypes(include='number').columns
    df[numeric_cols] = df[numeric_cols].fillna(0)

    # Add lowercase search column
    df['food_name_lower'] = df['food_name'].str.lower().str.strip()
    df['category'] = 'General'  # USDA data doesn't have categories

    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    conn = sqlite3.connect(db_path)
    df.to_sql('usda_nutrition', conn, if_exists='replace', index=False)
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_food_name "
        "ON usda_nutrition(food_name_lower)"
    )
    conn.commit()
    conn.close()
    print(f"Real USDA data loaded: {len(df)} ingredients.")
